import axios from 'axios';

async function testFullCheckout() {
  const baseURL = 'http://localhost:5001/api';
  console.log('1. Logging in as student (tcusub777@gmail.com)...');
  const loginRes = await axios.post(`${baseURL}/auth/login`, {
    email: 'tcusub777@gmail.com',
    password: 'Password123!',
  });
  const token = loginRes.data.accessToken;
  const headers = { Authorization: `Bearer ${token}` };
  console.log('Login successful!');

  console.log('\n2. Fetching courses to find a paid course...');
  const coursesRes = await axios.get(`${baseURL}/courses`);
  const course = coursesRes.data.courses.find((c: any) => c.price > 0);
  console.log(`Found paid course: "${course.title}" (ID: ${course.id}, Price: ${course.currency} ${course.price})`);

  console.log('\n3. Initializing Paystack Checkout via POST /api/payments/initialize...');
  const initRes = await axios.post(
    `${baseURL}/payments/initialize`,
    { courseId: course.id },
    { headers }
  );

  console.log('Initialization Status:', initRes.status);
  console.log('Response Payload:', initRes.data);
  console.log('\n[VERIFIED] Authorization URL generated by Paystack:', initRes.data.authorization_url);
}

testFullCheckout().catch(console.error);
